# Generated by Django 4.1 on 2023-03-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_userprofile_birthday_alter_userprofile_id_club_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='club',
            table='Club',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='club.club')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.user')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.user')),
            ],
            options={
                'db_table': 'Approval',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clubs', to='club.user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
